CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `cms`.`view_order` AS
    SELECT 
        `cms`.`order`.`order_id` AS `order_id`,
        `cms`.`order`.`customer_id` AS `customer_id`,
        `cms`.`order`.`customer_name` AS `customer_name`,
        `cms`.`order`.`customer_company` AS `customer_company`,
        `cms`.`order`.`customer_street_address` AS `customer_street_address`,
        `cms`.`order`.`customer_suburb` AS `customer_suburb`,
        `cms`.`order`.`customer_city` AS `customer_city`,
        `cms`.`order`.`customer_postcode` AS `customer_postcode`,
        `cms`.`order`.`customer_state` AS `customer_state`,
        `cms`.`order`.`customer_country` AS `customer_country`,
        `cms`.`order`.`customer_telephone` AS `customer_telephone`,
        `cms`.`order`.`email` AS `email`,
        `cms`.`order`.`delivery_name` AS `delivery_name`,
        `cms`.`order`.`delivery_company` AS `delivery_company`,
        `cms`.`order`.`delivery_street_address` AS `delivery_street_address`,
        `cms`.`order`.`delivery_suburb` AS `delivery_suburb`,
        `cms`.`order`.`delivery_city` AS `delivery_city`,
        `cms`.`order`.`delivery_postcode` AS `delivery_postcode`,
        `cms`.`order`.`delivery_state` AS `delivery_state`,
        `cms`.`order`.`delivery_country` AS `delivery_country`,
        `cms`.`order`.`billing_name` AS `billing_name`,
        `cms`.`order`.`billing_company` AS `billing_company`,
        `cms`.`order`.`billing_street_address` AS `billing_street_address`,
        `cms`.`order`.`billing_suburb` AS `billing_suburb`,
        `cms`.`order`.`billing_city` AS `billing_city`,
        `cms`.`order`.`billing_postcode` AS `billing_postcode`,
        `cms`.`order`.`billing_state` AS `billing_state`,
        `cms`.`order`.`billing_country` AS `billing_country`,
        `cms`.`order`.`payment_method` AS `payment_method`,
        `cms`.`order`.`date_purchased` AS `date_purchased`,
        `cms`.`order`.`orders_date_finished` AS `orders_date_finished`,
        `cms`.`order`.`order_price` AS `order_price`,
        `cms`.`order`.`shipping_cost` AS `shipping_cost`,
        `cms`.`order`.`shipping_method` AS `shipping_method`,
        `cms`.`order`.`shipping_duration` AS `shipping_duration`,
        `cms`.`order`.`order_information` AS `order_information`,
        `cms`.`order`.`is_seen` AS `is_seen`,
        `cms`.`order`.`coupon_code` AS `coupon_code`,
        `cms`.`order`.`coupon_amount` AS `coupon_amount`,
        `cms`.`order`.`free_shipping` AS `free_shipping`,
        `cms`.`order`.`customer_remark` AS `customer_remark`,
        `cms`.`order`.`create_date` AS `create_date`,
        `cms`.`order`.`create_by_id` AS `create_by_id`,
        `cms`.`order`.`edit_date` AS `edit_date`,
        `cms`.`order`.`edit_by_id` AS `edit_by_id`,
        `cms`.`order`.`status` AS `status`
    FROM
        (`cms`.`order`
        LEFT JOIN `cms`.`order_product` ON ((`cms`.`order`.`order_id` = `cms`.`order_product`.`order_id`)))